[package]
name = "jsonrpc_client"
version = "0.1.0"
edition = "2021"

[dependencies]
easy-jsonrpc-mw = "0.5.4"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = "1"
serde_json = "1"
